### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by codecowboy** [haegemon/jasmin-admin#1]
Could you add some simple installation documentation for this? I'm running the jasmin docker image.

**Comment by haegemon** [comment]
I'm sorry, but this package is unfinished now.

**Comment by farirat** [comment]
haegemon, i cant get your email from your github profile, please send me an email to discuss some work on jasmin, thx !

**Comment by haegemon** [comment]
Email sent

**Comment by farirat** [comment]
received nothing, where did you send ?

**Comment by haegemon** [comment]
I send email to     support@jasminsms.com with topic "Haegemon"
