### ISSUE TITLE
Which Laravel version are you running

### ISSUE THREAD

**Issue by juanantoniotv** [haegemon/jasmin-admin#2]
Hi, could you tel me which Laravel version are you running, I have some errors in v. Master, Thanks!

Declaration of App\Providers\EventServiceProvider::boot(Illuminate\Contracts\Events\Dispatcher $events) should be compatible with Illuminate\Foundation\Support\Providers\EventServiceProvider::boot()

**Comment by haegemon** [comment]
Hi, I running at Laravel 5.2.0 - 5.2.1
